name: responsive_reflow_example
description: Minimal example demonstrating responsive_reflow.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.6.1
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_reflow:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
